version: "3.9"

services:
  reyes-app:
    # aqui es donde la imagen debe de concidir 
    image: ghcr.io/<Themesenjer>/examen_devops_25-11-25:reyes-1.0.5
    deploy:
      replicas: 1
      labels:
        # Configuración de Traefik para el dominio
        - "traefik.enable=true"
        - "traefik.http.routers.reyes.rule=Host(`reyes.byronrm.com`)"
        - "traefik.http.routers.reyes.entrypoints=websecure"
        - "traefik.http.routers.reyes.tls.certresolver=myresolver"
        - "traefik.http.services.reyes.loadbalancer.server.port=5000"
    ports:
      # Mapeo de puerto directo solicitado (1987)
      - "1987:5000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true