name: Examen DevOps CI/CD

on:
  push:
    branches:
      - reyes

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and Test
        run: |
          pip install -r requirements.txt
          pytest

      - name: Lowercase Repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:reyes-1.0.5
          context: .

      # --- DESPLIEGUE ---
      
      # 6. Despliegue al VPS (CD)
      - name: Copy stack.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 1002 
          source: "stack.yml"
          target: "/home/${{ secrets.VPS_USER }}/examen_reyes"
          timeout: 120s # Aumentamos a 2 minutos
          command_timeout: 30m

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 1002
          script: |
            mkdir -p /home/${{ secrets.VPS_USER }}/examen_reyes
            cd /home/${{ secrets.VPS_USER }}/examen_reyes
            
            echo "Iniciando despliegue..."
            
            # Login
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull imagen
            docker pull ghcr.io/${{ env.REPO_NAME }}:reyes-1.0.5
            
            # Reiniciar Stack
            docker stack rm stack_reyes || true
            sleep 10
            docker stack deploy -c stack.yml stack_reyes